# Generated by Django 2.1.7 on 2019-11-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0002_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
