# Generated by Django 2.1.7 on 2019-11-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0003_auto_20191129_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('userid', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('nation', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='SIGNUP',
        ),
    ]
