# Generated by Django 2.1.7 on 2019-11-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0004_auto_20191129_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.EmailField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
