# Generated by Django 2.1.7 on 2019-11-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0006_new_neww'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='new',
        ),
        migrations.DeleteModel(
            name='neww',
        ),
    ]
