# Generated by Django 2.1.7 on 2019-12-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0008_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('userid', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
            ],
        ),
    ]
