# Generated by Django 2.1.7 on 2019-12-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0011_auto_20191202_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('userid', models.EmailField(max_length=35, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('conformpassword', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('nation', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Userdetails',
        ),
    ]
