# Generated by Django 2.1.7 on 2019-12-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0014_legalofficer_medicalofficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customsofficer',
            fields=[
                ('userid', models.EmailField(max_length=35, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Narcoticofficer',
            fields=[
                ('userid', models.EmailField(max_length=35, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Socialworker',
            fields=[
                ('userid', models.EmailField(max_length=35, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
    ]
