# Generated by Django 2.1.7 on 2019-12-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0015_customsofficer_narcoticofficer_socialworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customssignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Legalsignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medicalsignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Narcoticsignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Socialworkersignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Customsofficer',
        ),
        migrations.DeleteModel(
            name='Legalofficer',
        ),
        migrations.DeleteModel(
            name='Medicalofficer',
        ),
        migrations.DeleteModel(
            name='Narcoticofficer',
        ),
        migrations.DeleteModel(
            name='Socialworker',
        ),
    ]
