# Generated by Django 2.1.7 on 2019-12-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0016_auto_20191216_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customsofficer',
            fields=[
                ('userid', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Legalofficer',
            fields=[
                ('userid', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medicalofficer',
            fields=[
                ('userid', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Narcoticofficer',
            fields=[
                ('userid', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Socialworker',
            fields=[
                ('userid', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=35)),
                ('professional_summary', models.CharField(max_length=500)),
                ('core_qualification', models.CharField(max_length=200)),
                ('practice', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Customssignup',
        ),
        migrations.DeleteModel(
            name='Legalsignup',
        ),
        migrations.DeleteModel(
            name='Medicalsignup',
        ),
        migrations.DeleteModel(
            name='Narcoticsignup',
        ),
        migrations.DeleteModel(
            name='Socialworkersignup',
        ),
    ]
