# Generated by Django 2.1.7 on 2020-01-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0017_auto_20191230_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('event_date', models.DateTimeField(max_length=30)),
                ('venue', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=30)),
            ],
        ),
    ]
