# Generated by Django 2.1.7 on 2020-01-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0018_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('event_date', models.DateTimeField(verbose_name='eventdate')),
                ('venue', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
