# Generated by Django 2.1.7 on 2020-01-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0020_auto_20200106_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('event_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=30)),
            ],
        ),
    ]
