# Generated by Django 2.1.7 on 2020-01-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0021_prg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prg',
            new_name='Details',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
