# Generated by Django 2.1.7 on 2020-01-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latestapp', '0023_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('event_date', models.DateTimeField(max_length=20)),
                ('venue', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
